### ISSUE TITLE
TODO Entity - CRUD 기능 테스트 및 테스트 코드 작성

### ISSUE THREAD

**Issue by seoweed** [MTVS-3rd-TODORIAN/TODORIAN_BE#11]
# ✅기능 이슈

## Description

> 개발할 상세 기능을 적어 주세요
TODO Entity  CRUD 기능 테스트 및 테스트 코드 작성

<br>

## To Do
- [ ] TODO Service 로직 - 조회 테스트 코드 작성
- [ ] TODO Service 로직 - 생성 테스트 코드 작성
- [ ] TODO Service 로직 - 수정 테스트 코드 작성
- [ ] TODO Service 로직 - 삭제 테스트 코드 작성

<br>

## ETC

> 기타사항
